create additional purses during create\update
hiqdev/hipanel-module-client pull request #140
Opened 2021-05-24 14:03 UTC by bladeroot

2021-05-24 14:17 UTC, strorch approved these changes

2021-05-24 14:40 UTC, SilverFire requested changes

2021-05-24 14:40 UTC, SilverFire commented on src/views/client/_form.php
> +        'currencies_id',
Похоже, не используетс

2021-06-05 13:33 UTC, hiqsol approved these changes

2021-06-05 13:34 UTC, merged