fix message\redirect after password change
hiqdev/hipanel-module-client pull request #152
Opened 2021-06-24 11:15 UTC by bladeroot

2021-06-24 15:26 UTC, SilverFire requested changes

2021-06-24 15:26 UTC, SilverFire commented on src/controllers/ClientController.php
> +                'error' => Yii::t('hipanel:client', 'Error during password change'),
Такого перевода нет

2021-06-29 06:42 UTC, strorch approved these changes

2021-07-01 08:11 UTC, hiqsol approved these changes

2021-07-01 08:12 UTC, merged