fixed hiam site link generation
hiqdev/hipanel-module-client pull request #154
Opened 2021-07-01 06:03 UTC by strorch

2021-07-05 10:08 UTC, SilverFire commented on src/controllers/ClientController.php
> +        $url = 'http://' . Yii::$app->params['hiam.site'] . Url::to(array_merge(['/site/reset-password'], Yii::$app->request->get()));
Не согласен, см. https://github.com/hiqdev/hipanel-core/pull/186/files#r663808430

2021-07-05 10:08 UTC, SilverFire requested changes
Считаю что этого делать нельзя

2021-07-05 10:49 UTC, tafid commented on src/controllers/ClientController.php
> +        $url = 'http://' . Yii::$app->params['hiam.site'] . Url::to(array_merge(['/site/reset-password'], Yii::$app->request->get()));
поддерживаю

2021-07-08 05:43 UTC, hiqsol approved these changes

2021-07-09 13:29 UTC, merged