Feature. Massive delete clients by logins
hiqdev/hipanel-module-client pull request #157
Opened 2021-07-07 15:48 UTC by tafid

2021-07-08 07:49 UTC, strorch requested changes

2021-07-08 07:49 UTC, strorch commented on src/actions/DeleteClientsByLoginsAction.php
> +            if ($controller->request->isPost && $form->load($controller->request->post())) {
ще треба $form->validate()

2021-07-08 07:49 UTC, strorch commented on src/forms/DeleteClientsByLoginsForm.php
> +        return Yii::$app->cache->getOrSet([__CLASS__, __METHOD__, $logins], fn(): array => Client::find()->where([
а нашо кешувать клієнтів яких треба видалить?

2021-07-08 07:49 UTC, strorch commented on src/actions/DeleteClientsByLoginsAction.php
> +                Client::batchPerform('delete', $payload);
може хай апі відаляє по логінам? ато доп запрос по пошуку айдішніків робиться

2021-07-08 07:49 UTC, strorch commented on src/actions/DeleteClientsByLoginsAction.php
> +            if ($controller->request->isPost && $form->load($controller->request->post())) {
кстаті не обов*язково тут кидать ексепшн, якщо форма не провалідується то і вернуть помилку, а якщо апі верне еррор то ексепшна тут не буде вроді?

2021-07-08 12:18 UTC, tafid commented on src/forms/DeleteClientsByLoginsForm.php
> +        return Yii::$app->cache->getOrSet([__CLASS__, __METHOD__, $logins], fn(): array => Client::find()->where([
резонно, исправлю

2021-07-08 12:19 UTC, tafid commented on src/actions/DeleteClientsByLoginsAction.php
> +                Client::batchPerform('delete', $payload);
оно конечно умеет и по логинам, но я не хочу передавать туда не правильную инфу

2021-07-09 08:37 UTC, strorch commented on src/forms/DeleteClientsByLoginsForm.php
> +    public function getClients(): array
я не знаю вкусовщина це чи ні, але мені ще не нрав що тут модель форми шукає клієнтів, я б ці методи в клас екшона всунув. або до форми зробив клас валідатора, який провалідує логіни і видалить по логінах, і цей код би виконався при $form->validate()

2021-07-09 09:21 UTC, tafid commented on src/forms/DeleteClientsByLoginsForm.php
> +    public function getClients(): array
я с тобой не несогласен, но если бы задача была чуть более масштабная я бы так и сделал, но тут проще сделать так

2021-07-09 12:38 UTC, SilverFire requested changes

2021-07-09 12:50 UTC, strorch commented on src/forms/DeleteClientsByLoginsForm.php
> +    public function getClients(): array
та всмислі не згоден? згоден що робить запрос в базу з класа форми це нормально? якби не її2 то тобі б цього ніхто не дозволив)

2021-07-09 14:12 UTC, tafid commented on src/forms/DeleteClientsByLoginsForm.php
> +    public function getClients(): array
я же написал, - "НЕ НЕсогласен" )))

2021-07-12 07:14 UTC, strorch approved these changes

2021-07-14 10:25 UTC, hiqsol approved these changes

2021-07-14 10:25 UTC, merged