Hide system client init
hiqdev/hipanel-module-client pull request #159
Opened 2021-08-19 10:19 UTC by bladeroot

2021-08-20 07:14 UTC, strorch approved these changes

2021-08-20 15:02 UTC, SilverFire requested changes

2021-08-20 15:02 UTC, SilverFire commented on src/models/ClientSearch.php
> +    const DEBT_LABEL_DEBITOR = 'debitor';
```suggestion
    const DEBT_LABEL_DEBTOR = 'debtor';
```

В английсокм языке нет слова `Debitor`

2021-08-20 15:02 UTC, SilverFire commented on src/views/client/_search.php
> +<div class="col-md-4 col-sm-6 col-xs-12">
Этот и нижестоящие фильтры предлагаю спрятать от непривилегированных пользователей.

2021-08-23 15:25 UTC, hiqsol approved these changes

2021-08-31 12:44 UTC, SilverFire commented on src/views/client/_search.php
> +<div class="col-md-4 col-sm-6 col-xs-12">
@bladeroot что скажешь?

2021-08-31 12:46 UTC, bladeroot commented on src/views/client/_search.php
> +<div class="col-md-4 col-sm-6 col-xs-12">
Ничего. Право придумать бы стоит для начала. И вот добавлять их через ids еще то веселье =(

2021-09-03 09:59 UTC, hiqsol commented on src/views/client/_search.php
> +<div class="col-md-4 col-sm-6 col-xs-12">
поставь сейчас `can('support')`

2021-09-03 10:31 UTC, hiqsol approved these changes

2021-09-03 10:32 UTC, hiqsol commented on src/views/client/_search.php
> +<div class="col-md-4 col-sm-6 col-xs-12">
`can('support')` для операций которые вносят изменения - это точно отказались
а тут я пока не знаю как такое право назвать
+ не вижу смысла
+ надо срочно
короче делай, если потом сообразим - исправить не сложно

2021-09-03 10:32 UTC, merged