New test Added admin/DomainSettingsCest
hiqdev/hipanel-module-client pull request #178
Opened 2021-11-06 10:47 UTC by Drakorgaur

2021-11-06 10:49 UTC, Drakorgaur commented on tests/acceptance/admin/client/profile-usermenu/DomainSettingsCest.php
> +            $fieldId = strtolower(preg_replace('(\s\w+)', '', $label));
не супер уверен по поводу этой строки(1), может есть метод красивее.
через провайдер я получил 'Registrant contact', а у селектора для Select2 xpath select[id*=registrant].

2021-11-06 10:51 UTC, Drakorgaur commented on tests/acceptance/admin/client/profile-usermenu/DomainSettingsCest.php
> +            $I->seeElement((new Select2($I, "select[id*=$fieldId]"))->getSelector());
не супер уверен по поводу этой строки(2), можно было просто запихнуть seeElement("select[id*=$fieldId]"), я подумал, так просто код будет понятнее и читабельнее.

2021-11-08 08:40 UTC, tafid requested changes

2021-11-08 08:40 UTC, tafid commented on tests/acceptance/admin/client/profile-usermenu/DomainSettingsCest.php
> +            $fieldId = strtolower(preg_replace('(\s\w+)', '', $label));
так оно работает?

2021-11-08 08:40 UTC, tafid commented on tests/acceptance/admin/client/profile-usermenu/DomainSettingsCest.php
> +            $I->seeElement((new Select2($I, "select[id*=$fieldId]"))->getSelector());
так оно работает?

2021-11-08 12:50 UTC, Drakorgaur commented on tests/acceptance/admin/client/profile-usermenu/DomainSettingsCest.php
> +            $fieldId = strtolower(preg_replace('(\s\w+)', '', $label));
канеш) я ж проверяю тесты перед пушем :)

2021-11-08 12:52 UTC, Drakorgaur commented on tests/acceptance/admin/client/profile-usermenu/DomainSettingsCest.php
> +            $I->seeElement((new Select2($I, "select[id*=$fieldId]"))->getSelector());
ну да, а че нет то) 
Я к тому что я мог бы просто написать  $I->seeElement("select[id*=$fieldId]"). Без создания объекта Select2. Но подумал, что так тест понятнее и читабельнее.

2021-11-09 13:02 UTC, tafid approved these changes

2021-11-10 13:40 UTC, merged