Set additional information
hiqdev/hipanel-module-client pull request #182
Opened 2021-11-12 11:15 UTC by Drakorgaur

2021-11-14 12:14 UTC, Drakorgaur commented on tests/acceptance/manager/profile-usermenu/AdditionalInformationCest.php
> +        if ($username === 'hipanel_test_manager') {
Тут следствие из описание. Я могу сделать, чтоб тест переходил просто по ID hipanel_test_user к примеру, но хардкод вроде не очень хорошо.

2021-11-15 16:50 UTC, tafid requested changes

2021-11-15 16:50 UTC, tafid commented on tests/acceptance/manager/profile-usermenu/AdditionalInformationCest.php
> +namespace hipanel\modules\client\tests\acceptance\admin\client\profile\usermenu;
а почему файл лежит в папке "manager", а нймспейс у файла "admin"?

2021-11-15 16:53 UTC, tafid commented on tests/acceptance/manager/profile-usermenu/AdditionalInformationCest.php
> +        $I->waitForElementVisible("//button[contains(text(),'Confirm')]");
во всех таких случаях  лучше удалить лишние пробелы в строке с помощью функции normalize-space() ```//button[contains(text(),'Confirm')]``` -> ```//button[contains(normalize-space(text()),'Confirm')]```

2021-11-15 16:56 UTC, tafid requested changes

2021-11-15 16:56 UTC, tafid commented on tests/acceptance/manager/profile-usermenu/AdditionalInformationCest.php
> +            $I->click("//div[@class='modal-body']/form //tbody//tr[last()] //button");
Старайся всегда писать селекторы не по полному совпадению. Лучше написать как то так: ```[contains(@class, ’modal-body’)]``` В любой момент в этой строке кто то добавит дополнительный класс и она уже не будет находиться

2021-11-15 16:57 UTC, tafid requested changes

2021-11-15 16:57 UTC, tafid commented on tests/acceptance/manager/profile-usermenu/AdditionalInformationCest.php
> +        $selector = "//table[@class='table table-striped']";
Старайся всегда писать селекторы не по полному совпадению. Лучше написать как то так: ```[contains(@class, ’ЫЫЫЫ’)]``` В любой момент в этой строке кто то добавит дополнительный класс и она уже не будет находиться

2021-11-15 16:57 UTC, tafid commented on tests/acceptance/manager/profile-usermenu/AdditionalInformationCest.php
> +        $formSelector = "//div[@class='modal-body']/form";
Старайся всегда писать селекторы не по полному совпадению. Лучше написать как то так: ```[contains(@class, ’ЫЫЫЫ’)]``` В любой момент в этой строке кто то добавит дополнительный класс и она уже не будет находиться

2021-11-16 20:29 UTC, merged